source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'activesupport'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'tux'
gem 'shotgun'

group :test do
    gem 'capybara'
    gem 'database_cleaner'
    gem 'rspec'
    gem 'rack-test'
end