source 'https://rubygems.org'
ruby '1.9.3'

gem 'sinatra'
gem 'datamapper'
gem 'heroku'

group :production do
  gem 'pg'
  gem 'dm-postgres-adapter'
end

group :development, :test do
    gem 'sqlite3'
    gem 'dm-sqlite-adapter'
end